language: python

sudo: required
dist: trusty

python:
  - 2.7
  - 3.4

env:
  QT_VERBOSE=true

virtualenv:
  # apt-install ends up amongst system packages
  system_site_packages: true

addons:
  apt:
    packages:


install:
  # Based on http://stackoverflow.com/a/24545890/478949
  - sudo apt-get install qt4-qmake libqt4-dev python-qt4 python-pyside
  - python -c "import PySide;print(PySide)"
  - python -c "import PyQt4;print(PyQt4)"

# Enable virtual framebuffer, this way we can instantiate
# a QApplication and create widgets.
# https://docs.travis-ci.com/user/gui-and-headless-browsers/
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script:
  - nosetests --verbose
