language: python

python:
  - 2.7

virtualenv:
  # apt packages ends up amongst system packages
  system_site_packages: true

addons:
  apt:
    packages:
    - qt4-qmake
    - libqt4-dev
    - python-qt4
    # - python-pyside  # not whitelisted for some reason

install:
  # Based on http://stackoverflow.com/a/24545890/478949
  - pip install PySide --no-index --find-links https://parkin.github.io/python-wheelhouse/;

script:
  - nosetests --verbose
