name: Run PySide6 Tests

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  test:
    runs-on: ubuntu-22.04

    env:
      QT_PREFERRED_BINDING: PySide6
      QT_QPA_PLATFORM: minimal
      QT_VERBOSE: 1
      PYTHONPATH: "${{ github.workspace }}"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install EGL mesa
        run: |
          sudo apt-get update -y -qq
          sudo apt-get install -y -qq libegl1-mesa libegl1-mesa-dev libgl1-mesa-glx libgl1-mesa-dev

      - name: Install GUI libs
        run: |
          sudo apt-get install -y -qq libxcb-xinerama0
          sudo apt-get install -y -qq libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-xfixes0 libxcb-cursor0 

      - name: Pip install . 
        run: |
          python3.10 -m pip install .

      - name: Pip install PySide6 and dependencies 
        run: |
          python3.10 -m pip install PySide6 nose2 nosepipe six packaging setuptools wheel

      - name: Testing implementation..
        run: |
          python3.10 -m nose2 --verbose tests
        
      - name: Building caveats..
        run: |
          python3.10 -u build_caveats.py

      - name: Testing caveats..
        run: |
          python3.10 -m nose2 --verbose test_caveats

      - name: Testing examples..
        run: |
          python3.10 -m nose2 --verbose examples.loadUi.baseinstance1
          python3.10 -m nose2 --verbose examples.QtSiteConfig.main
